// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC25D8mGW7xbFbTvCw-vbV7ui4GajdXXWA',
    appId: '1:342385054887:android:3171fcc6606be4a7583782',
    messagingSenderId: '342385054887',
    projectId: 'flutter-notes-c217e',
    storageBucket: 'flutter-notes-c217e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7tr236XElxg88xrh1S0hmXDhK8OAKcck',
    appId: '1:342385054887:ios:2053a292271d323c583782',
    messagingSenderId: '342385054887',
    projectId: 'flutter-notes-c217e',
    storageBucket: 'flutter-notes-c217e.firebasestorage.app',
    androidClientId: '342385054887-q9bu1ngtdk8tuq68plqqc2gsr17ftffn.apps.googleusercontent.com',
    iosClientId: '342385054887-t9svfkis7v65mphke6v19ok7fmnqnv45.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutsi',
  );

}